### ISSUE TITLE
Suduku

### ISSUE THREAD

**Issue by Fmiri08** [Teaching-projects/SOE-ProgAlap1-Beadando-Sudoku-Farkas#1]
Jó szerencsét! 
kicsit késésben, de szerintem elkészültem a projektemmel. Rá tudnál nézni, hogy mit alakítsak/tegyek bele még a holnapi nap? 
Előre is köszönöm szépen!
Ui.: a pydocot holnap pótolom hozzá

**Comment by hegyhati** [comment]
No, hat a program nem tul osszetett.

a check fuggvenyedben a -1-et is belerakod a set-be, bar ha jol latom, ezt csak akkor hivod meg, amikor mar kitoltott a tabla.

miert csinalsz deepcopy-t?

Amit lehet, azt jo volna pdoc-kal teszteltetni.

Illetve mar jo volna, ha kozben is szolna egy uj lepesnel, ha az mar rossz ugye. 

Normal esetben irnek egy szep listat, hogy mit kellene javitani, de ugye ez most mar utolso vizsgaalkalom, az idonk limitalt (nekem is), szoval fussunk ugy neki a dolognak, hogy Te hanyast szeretnel megcelozni?

**Comment by Fmiri08** [comment]
a chek függvényt pont így küszöböltem ki hogy ne rakja bele a -1-et, hogy csak a végén hívom meg

próbáltam másolni a függvényt és teljes másolatot készített próbáltam kiküszöbölni, néztem az órai anyagot, de nem találtam a deepcopy-val működött.

igazából egy 3-ast szeretnék megcélozni, ha ez lehetséges

**Comment by hegyhati** [comment]
En is a kozepest ereztem most meg a zh-t is picit figyelembe veve helyenvalonak. Ha ezzel ki tudsz egyezni, akkor legyen az. Ettol fuggetlenul pdoc-ot es egyebeket azert meg tessek gyakorolni :-)

**Comment by Fmiri08** [comment]
Rendben! köszönöm szépen!
